#!/usr/bin/env bash

################################################
#        Custom Arch installer script          #
################################################

# Prompt to gather data
function prompt {
    local message=$1
    local variable=$2
    local default=$3
    tput setaf 15
    read -p "${message} (default: ${default}): " value
    tput sgr0
    eval $variable=${value:-$default}
}

# Cool logo message
function logo() {
    local text=$1

    local blue=$(tput setaf 4; tput bold)
    local indigo=$(tput setaf 5; tput bold)
    local text_color=$(tput bold)

    local screen_width=$(tput cols)
    local logo="
 █████╗ ██████╗  ██████╗██╗  ██╗██╗   ██╗
██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
███████║██████╔╝██║     ███████║ ╚████╔╝ 
██╔══██║██╔══██╗██║     ██╔══██║  ╚██╔╝  
██║  ██║██║  ██║╚██████╗██║  ██║   ██║   
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   ╚═╝   
"
    local logo_width=$(echo "$logo" | awk '{ if (length > max) max = length } END { print max }')

    clear

    IFS=$'\n'
    printf "\n"
    for line in $logo
    do
        printf "%*s%s\n" $((($screen_width - ${#line} - 1) / 2)) "" "$indigo$line"
    done

    printf "\n%*s%s%s%*s\n\n" $((($screen_width - ${#text} - 1) / 2)) "" "$blue" "$text" $((($screen_width + ${#text} + ${#text} - $logo_width) / 2)) ""

    tput sgr0
}

logo "Press any key to continue..."
read

# Information gathering
prompt "Hostname" HOSTNAME macbook
prompt "Root password" MASTER_PASSWORD "None"
prompt "Username" USERNAME "None"
prompt "Password" PASSWORD "None"
prompt "Timezone" TIMEZONE "Africa/Algiers"

select AUDIO_SERVER in "Pipewire (New, suitable for modern multimedia needs)" "Pulseaudio (Old, suitable for traditional Linux audio needs)"; do
    case $AUDIO_SERVER in
        "") AUDIO_SERVER="pipewire"; break;;
        "Pipewire (New, suitable for modern multimedia needs)") AUDIO_SERVER="pipewire"; break;;
        "Pulseaudio (Old, suitable for traditional Linux audio needs)") AUDIO_SERVER="pulseaudio"; break;;
    esac
done

devices=$(lsblk -o NAME,SIZE | grep -e '^sd\|^nvme')
PS3="Select a disk: "
echo "Available devices:"
options=()
while read -r line; do
    disk=$(echo $line | awk '{print $1}')
    size=$(echo $line | awk '{print $2}')
    options+=("$disk ($size)")
done <<< "$devices"
options+=("Quit")
select device in "${options[@]}"; do
    case $device in
        "") echo "Invalid selection";;
        "Quit") exit;;
        *) DISK=$(echo $device | awk '{print $1}'); break;;
    esac
done

logo "Formating Disks..."
mkdir /mnt &>/dev/null
swapoff /mnt/swapfile
umount -Af --recursive /mnt
sgdisk -Z ${DISK}
sgdisk -a 2048 -o ${DISK}
sgdisk -n 1::+256M  --typecode=1:AF00 --change-name=1:'BOOT'  ${DISK}
sgdisk -n 2::-0     --typecode=2:8300 --change-name=2:'ROOT' ${DISK}
partprobe ${DISK}

logo "Creating Filesystems..."
mkfs.fat -F 32 ${DISK}1
fatlabel ${DISK}1 BOOT
mkfs.ext4 -L ROOT ${DISK}2
mount /dev/disk/by-label/ROOT /mnt
mkdir -p /mnt/boot/efi
mount /dev/disk/by-label/BOOT /mnt/boot/efi

logo "Create a swap partition 4Gb..."
dd if=/dev/zero of=/mnt/swapfile bs=1M count=1024 status=progress
chmod 600 /mnt/swapfile
chown root /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/swapfile
if ! grep -qs '/mnt' /proc/mounts; then
  (sleep 3 && reboot )
fi

logo "Archy installation..."
pacstrap /mnt base base-devel ${KERNEL} ${KERNEL}-headers linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

logo "Chrooting Into The New Installation..."
cp -fvr /mnt/etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist.backup
cp -fvr /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
( arch-chroot /mnt /postinstall ) |& tee postinstall.log
cp -fvr postinstall.log /mnt




echo -ne "
------------------------------------------------------------------------------------------
                                Setup Language And Locale
------------------------------------------------------------------------------------------
"
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
ln -s /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
hwclock --systohc
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf

echo -ne "
------------------------------------------------------------------------------------------
                                     Adding User
------------------------------------------------------------------------------------------
"
groupadd libvirt
useradd -m -G wheel,audio,video,libvirt -s /bin/bash --badname ${USERNAME}
ENCRYPTED_MASTER_PASSWORD=$(openssl passwd -6 -salt 'salt' ${MASTER_PASSWORD})
ENCRYPTED_PASSWORD=$(openssl passwd -6 -salt 'salt' ${PASSWORD})
usermod --password "${ENCRYPTED_MASTER_PASSWORD}" root
usermod --password "${ENCRYPTED_PASSWORD}" ${USERNAME}
echo "${HOSTNAME}" > /etc/hostname

echo -ne "
------------------------------------------------------------------------------------------
                                 Creating GRUB Boot Menu
------------------------------------------------------------------------------------------
"
pacman -S --noconfirm --needed grub os-prober efibootmgr dhcpcd
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

echo -ne "
------------------------------------------------------------------------------------------
                                  Installing packages
------------------------------------------------------------------------------------------
"
if [[ ! -f "packages" ]]; then
  echo "Error: packages file not found."
  exit 1
fi
while read line
do
  if [[ $line == "" ]] || [[ $line == \#* ]]; then
    continue
  fi
  pacman -Sy --noconfirm --needed "$line"
done < packages

echo -ne "
------------------------------------------------------------------------------------------
                                     Switch shell
------------------------------------------------------------------------------------------
"
chsh -s ${SHELL} root
chsh -s ${SHELL} ${USERNAME}

echo -ne "
------------------------------------------------------------------------------------------
                               Managing Essential Services
------------------------------------------------------------------------------------------
"
systemctl disable --now transmission.service
systemctl enable  --now dhcpcd.service
systemctl enable  --now NetworkManager.service

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
echo -ne 'KEYMAP="us"
FONT="ter-132b"
' > /etc/vconsole.conf

echo -ne "
------------------------------------------------------------------------------------------
                                Add no password sudo rights
------------------------------------------------------------------------------------------
"
sed -ni "/^root/{a\
  ${USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL
p}" /etc/sudoers




logo "Done - Please Eject Install Media"
# umount -R /mnt
# reboot
