#!/usr/bin/env bash

################################################
#        Custom Arch installer script          #
################################################

# Prompt to gather data
function prompt {
    local message=$1
    local variable=$2
    local default=$3
    tput setaf 15
    read -p "${message} (default: ${default}): " value
    tput sgr0
    eval $variable=${value:-$default}
}

# Cool logo message
function logo() {
    local text=$1

    local blue=$(tput setaf 4; tput bold)
    local indigo=$(tput setaf 5; tput bold)
    local text_color=$(tput bold)

    local screen_width=$(tput cols)
    local logo="
 █████╗ ██████╗  ██████╗██╗  ██╗██╗   ██╗
██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
███████║██████╔╝██║     ███████║ ╚████╔╝ 
██╔══██║██╔══██╗██║     ██╔══██║  ╚██╔╝  
██║  ██║██║  ██║╚██████╗██║  ██║   ██║   
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   ╚═╝   
"
    local logo_width=$(echo "$logo" | awk '{ if (length > max) max = length } END { print max }')

    clear

    IFS=$'\n'
    printf "\n"
    for line in $logo
    do
        printf "%*s%s\n" $((($screen_width - ${#line} - 1) / 2)) "" "$indigo$line"
    done

    printf "\n%*s%s%s%*s\n\n" $((($screen_width - ${#text} - 1) / 2)) "" "$blue" "$text" $((($screen_width + ${#text} + ${#text} - $logo_width) / 2)) ""

    tput sgr0
}

logo "Press any key to continue..."
read

logo "Formating Disks..."
mkdir /mnt &>/dev/null
swapoff /mnt/swapfile
umount -Af --recursive /mnt
sgdisk -Z ${DISK}
sgdisk -a 2048 -o ${DISK}
sgdisk -n 1::+256M  --typecode=1:AF00 --change-name=1:'BOOT'  ${DISK}
sgdisk -n 2::-0     --typecode=2:8300 --change-name=2:'ROOT' ${DISK}
partprobe ${DISK}

logo "Creating Filesystems..."
mkfs.fat -F 32 ${DISK}1
fatlabel ${DISK}1 BOOT
mkfs.ext4 -L ROOT ${DISK}2
mount /dev/disk/by-label/ROOT /mnt
mkdir -p /mnt/boot/efi
mount /dev/disk/by-label/BOOT /mnt/boot/efi

logo "Create a swap partition 4Gb..."
dd if=/dev/zero of=/mnt/swapfile bs=1M count=1024 status=progress
chmod 600 /mnt/swapfile
chown root /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/swapfile
if ! grep -qs '/mnt' /proc/mounts; then
  (sleep 3 && reboot )
fi

logo "Archy installation..."
pacstrap /mnt base base-devel ${KERNEL} ${KERNEL}-headers linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

echo -ne "
------------------------------------------------------------------------------------------
                           Chrooting Into The New Installation
------------------------------------------------------------------------------------------
"
cp -fvr /mnt/etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist.backup
cp -fvr /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
cp -fvr /root/archy/postinstall /root/archy/packages /root/archy/.env /mnt
( arch-chroot /mnt /postinstall ) |& tee postinstall.log
cp -fvr postinstall.log /mnt

echo -ne "
------------------------------------------------------------------------------------------
                               Automated Archy Installer
------------------------------------------------------------------------------------------
                            Done - Please Eject Install Media

"
# umount -R /mnt
# reboot
