#!/usr/bin/env bash

################################################
#                                              #
# Create a .env file containing these options: #
#                                              #
################################################
#
# USERNAME=<New user name>
# PASSWORD=<New user password>
# HOSTNAME=<Hostname eg: macbook>
# SHELL=<eg: /bin/bash>
# TOKEN=<Your Github token (PAT)>
# DISK=<eg: /dev/sda>
# MOUNT_OPTIONS=<eg for ssd add: "noatime,ssd,...">
# FS=<Filesystem eg: ext4, btrfs...>
# TIMEZONE=<eg: Europe/Paris>
# KEYMAP=<eg: us,uk,es...>

source /root/.env

# Logo
clear
echo -ne "
------------------------------------------------------------------------------------------
                                Archy Post-Installation
------------------------------------------------------------------------------------------

                        Setting up archy custom configuration...
"

echo -ne "
------------------------------------------------------------------------------------------
                                Setup Language And Locale
------------------------------------------------------------------------------------------
"
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
timedatectl --no-ask-password set-timezone ${TIMEZONE}
timedatectl --no-ask-password set-ntp 1
localectl --no-ask-password set-locale LANG="en_US.UTF-8" LC_TIME="en_US.UTF-8"
ln -s /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
localectl --no-ask-password set-keymap ${KEYMAP}
hwclock --systohc
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

echo -ne "
------------------------------------------------------------------------------------------
                                     Adding User
------------------------------------------------------------------------------------------
"
pwconv
echo "${USERNAME}:${PASSWORD}" | chpasswd
echo "${HOSTNAME}" > /etc/hostname

echo -ne "
------------------------------------------------------------------------------------------
                                 Creating GRUB Boot Menu
------------------------------------------------------------------------------------------
"
pacman -S --noconfirm --needed grub os-prober efibootmgr
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

echo -ne "
------------------------------------------------------------------------------------------
                               Managing Essential Services
------------------------------------------------------------------------------------------
"
systemctl disable --now transmission.service
systemctl disable --now dhcpcd.service
systemctl enable --now NetworkManager.service

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
echo -ne 'KEYMAP="us"
FONT="ter-v32b"
' > /etc/vconsole.conf


echo -ne "
------------------------------------------------------------------------------------------
                                   Disabling Screen Tear
------------------------------------------------------------------------------------------
"
# Adding TearFree option
echo -ne 'Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "TearFree" "true"
EndSection
' > /etc/X11/xorg.conf.d/20-intel.conf

echo -ne "
------------------------------------------------------------------------------------------
                                    Slock Configuration
------------------------------------------------------------------------------------------
"
# Adding slock service
echo -ne '[Unit]
Description=Lock X session using slock for user %i
Before=sleep.target

[Service]
User=%i
Environment=DISPLAY=:0
ExecStartPre=/usr/bin/xset dpms force suspend
ExecStart=/usr/local/bin/slock

[Install]
WantedBy=sleep.target
' > /etc/systemd/system/slock@.service

echo -ne "
------------------------------------------------------------------------------------------
                               Updating Touchpad Configuration
------------------------------------------------------------------------------------------
"
# Touchpad configuration
echo -ne 'Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "Tapping" "True"
    Option "TappingDrag" "True"
    Option "ScrollMethod" "Twofinger"
    Option "NaturalScrolling" "False"
    Option "DisableWhileTyping" "False"
    Driver "libinput"
EndSection
' > /etc/X11/xorg.conf.d/40-libinput.conf
